sources:
  - name: coupon-finance
    handler:
      graphql:
        endpoint: '{context.url:https://subgraph.satsuma-prod.com/f6a8c4889b7b/clober/coupon-subgraph/api}'
    transforms:
      - autoPagination: { }

documents:
  - ./src/api/**/*.graphql


codegen:
  contextType: 'MeshContext & { url: string }'
